# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimationDays', models.CharField(max_length=6)),
                ('person1', models.CharField(default=0, max_length=100)),
                ('person2', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
