# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='person1',
            new_name='p1End',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='person2',
            new_name='p1First',
        ),
        migrations.AddField(
            model_name='task',
            name='p1Last',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='p1Start',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='p2End',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='p2First',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='p2Last',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='p2Start',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
